name: Lighthouse CI
on:
  push:
    branches:
      - master
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: |
            https://connorads.pages.dev
          temporaryPublicStorage: true