name: Lighthouse CI
on:
  push:
    branches:
      - master
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@10.1.0
        with:
          urls: |
            https://connoradams.co.uk
          temporaryPublicStorage: true
